### ISSUE TITLE
Add missing hymn number to titles

### ISSUE THREAD

**Issue by TinasheMzondiwa** [TinasheMzondiwa/cis-hymnals#14]
Recently added hymnals in this [PR](https://github.com/TinasheMzondiwa/cis-hymnals/pull/12) are all missing the number in the titles.

Titles should be the first line in the format:
`### 1 Title of the hymn` if markdown or
`<h1><b>1 Title of the hymn.</b></h1>` if html.

![android](https://github.com/TinasheMzondiwa/cis-hymnals/assets/5994683/a536133c-834c-4e50-bdf1-e5b672cf421e)

**Comment by TinasheMzondiwa** [comment]
@Burkifa23 Could you please look into this?

**Comment by Burkifa23** [comment]
I will work on this
Sorry I didn't notice this

**Comment by Burkifa23** [comment]
Greetings @TinasheMzondiwa.
It's done.
