### ISSUE TITLE
Typos in the Sepedi hymnal

### ISSUE THREAD

**Issue by defxLovet** [TinasheMzondiwa/cis-hymnals#24]
**Where is the typo?**
sepedi.json
Hymnal name name is Kreste Ka Kopelo
Hymn number: I browsed through the sepedi.json file fixing some errors and typos as I noticed them

**Describe the typo**
For example, hymn 3 uses 'to' for 'tlo'; this is common through the hymnal.
Hymn 12 last stanza has 'Lent5hitSwe' and a few other typos in the same.
I went through the whole file fixing such errors as I noticed them

**Expected behaviour**
Fixed typos

**Screenshots**
I will add screenshots of a few instances

hymn3
![Screenshot_20240407_113155_com tinashe christInSong 2](https://github.com/TinasheMzondiwa/cis-hymnals/assets/107896455/3f05b95c-d0e2-440c-966a-105661665bf4)

hymn 12
![Screenshot_20240407_092604_com tinashe christInSong 1](https://github.com/TinasheMzondiwa/cis-hymnals/assets/107896455/3391b387-d57a-4062-8e36-087ec4d3dbce)

hymn154
![Screenshot_20240407_083955_com tinashe christInSong 1](https://github.com/TinasheMzondiwa/cis-hymnals/assets/107896455/be910afc-ac7f-4d89-b0f4-d764678a10e4)

The above cases are for illustration but I went through the whole file picking and fixing such instances as I noticed them

**Smartphone (please complete the following information):**
 - Device: Huawei P30 Lite
 - Version [12]

**Additional context**
I downloaded a copy of sepedi.json and browsed through the file fixing typos as I noticed them. The only changes were such instances of typos so the file should still satisfy formatting and other requirements
I hereto attached

[sepedi.json](https://github.com/TinasheMzondiwa/cis-hymnals/files/14968140/sepedi.json)

file  reflecting the changes 

hymn 96 below cuts the last line on the last stanza such that scrolling further up in portrait can not bring the line to full view

![Screenshot_20240407_101126_com tinashe christInSong 1](https://github.com/TinasheMzondiwa/cis-hymnals/assets/107896455/d9966a2d-d889-43f9-a221-0d32b35e9f91)

**Comment by defxLovet** [comment]
Here is the correct reference to hymn 3
hymn3
![Screenshot_20240407_113155_com tinashe christInSong 1](https://github.com/TinasheMzondiwa/cis-hymnals/assets/107896455/0deeaab3-a7ee-4cd3-885b-9b7ed7110d01)

hymn 96 below cuts the last line on the list stanza such that scrolling further up in portrait can not bring the line to full view
![Screenshot_20240407_101126_com tinashe christInSong 1](https://github.com/TinasheMzondiwa/cis-hymnals/assets/107896455/d9966a2d-d889-43f9-a221-0d32b35e9f91)

**Comment by TinasheMzondiwa** [comment]
Closed in #25
