### ISSUE TITLE
Kinyarwanda hymnal

### ISSUE THREAD

**Issue by Burkifa23** [TinasheMzondiwa/cis-hymnals#8]
**Describe the new language you'd like**
I want to contribute the Kinyarwanda hymnal which is a language spoken in Rwanda and the SDA hymnal is called `Indirimbo zo guhimbaza Imana`. 
---
name: Kinyarwanda
about: Suggest a new language / hymnal
title: 'Indirimbo zo Guhimbaza Imana'
---

**Source files**
Do you already have words for this new hymnal?
I have it on my computer and you can also find it online too at [this link.](https://bibiliya.com/songs/guhimbaza/). To make it easier for you, I can make a pull request after am done with the file name called "kinyarwanda.json" which follows the structure and markdown of all other files and also ensure no typos exist.

Do you have permission for us to use this hymnal?
I may not have permission to do so since am just a volunteer.

**Additional context**
I would also like to contribute later other hymns later on, such as French, Kirundi which is spoken in Burundi and so many other SDA hymns.

Looking forward to work with you all, @TinasheMzondiwa,  @CrudeRags and @DevAgani.
May God bless you all!

**Comment by TinasheMzondiwa** [comment]
Thank you @Burkifa23.
Go ahead and submit the file when you're ready 🙏🏾

**Comment by Burkifa23** [comment]
Thank you @TinasheMzondiwa 
Just one more thing, is the process.py supposed to extract content from a source file or it's used for something else?

**Comment by TinasheMzondiwa** [comment]
That was used to convert some content from html to markdown
